networks:
  dev:
    driver: bridge

services:
  nginx:
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'  # Конфигурация NGINX
      - './index.html:/usr/share/nginx/html/index.html'  # Фронтенд
      - '/home/admin/certs/easydev:/usr/local/bin/certs'  # Монтирование сертификатов
      - './certs:/usr/local/bin/certs'  # Монтирование сертификатов
    depends_on:
      - postgres
      - backend-v1
      - backend-v2
      - frontend
    networks:
      - dev


  postgres:
    image: postgres
    container_name: easydev-postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    stop_grace_period: 1m
    environment:
      POSTGRES_USER: "easydev"
      POSTGRES_PASSWORD: "hoyCeka8"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
  backend-v1:
    build:
      context: ./v1
    environment:
      - CONFIG_PATH=/usr/local/bin/config/prod.yaml
    networks:
      - dev

  backend-v2:
    build:
      context: ./v2
    environment:
      - CONFIG_PATH=/usr/local/bin/config/prod.yaml
    networks:
      - dev

  frontend:
    volumes:
      - /home/admin/frontend:/mnt/frontend
    build:
      context: ./frontend
    networks:
      - dev