networks:
  easydev-prod:
    driver: bridge

services:
  nginx:
    container_name: easydev-nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/home/admin/certs/easydev:/usr/local/bin/certs'
    depends_on:
      - postgres
      - backend-v1
      - backend-v2
      - frontend
    restart: always
    networks:
      - prod

  postgres:
    image: postgres
    container_name: easydev-postgres
    ports:
      - '5433:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    stop_grace_period: 1m
    environment:
      POSTGRES_USER: "easydev"
      POSTGRES_PASSWORD: "hoyCeka8"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
    restart: always
    networks:
      - prod

  backend-v1:
    build:
      context: ./v1
    environment:
      - CONFIG_PATH=config/prod.yaml
    depends_on:
      - postgres
    restart: always
    networks:
      - prod

  backend-v2:
    build:
      context: ./v2
    environment:
      - CONFIG_PATH=config/prod.yaml
    depends_on:
      - postgres
    restart: always
    networks:
      - prod

  frontend:
    volumes:
      - /home/admin/frontend:/mnt/frontend
    build:
      context: ./frontend
    restart: always
    networks:
      - prod