env: "dev" # local, dev, prod
dbstring: "host=postgres port=5432 user=easydev password=hoyCeka8 dbname=postgres sslmode=disable"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "s4bb4t"